name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.2.3

jobs:
  release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Build and publish Electron app
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish
      
    - name: Upload release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-files
        path: release/
        retention-days: 30
